---
- hosts: all
  become: true
  vars:
    user_name: user

  tasks:
  - name: Installation pip3, python3, and java-jdk for Ubuntu
    apt:
      name:
        - python3
        - python3-pip
        - openjdk-11-jdk
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Installation pip3, python3, and java-jdk for CentOS
    dnf:
      name:
        - python3-pip
        - python3
        - java-11-openjdk-devel
      state: present
    when: ansible_distribution == "CentOS"

  - name: default MOTD
    copy:
      content: "Ansible Managed node by Cabario"
      dest: /etc/motd

  - name: Create user
    ansible.builtin.user:
      name: cabario
      comment: bhenjie
      state: present
      createhome: yes
      shell: /bin/bash
